<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <RootNamespace>Stellar.S3P3RaidPortalHelper</RootNamespace>
        <PackageId>Stellar.S3P3RaidPortalHelper</PackageId>
        <Version>1.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Stellar.Abstractions" Version="2.4.0" />
        <PackageReference Include="Stellar.Plugin.InteropRefs" Version="2.4.0" />
    </ItemGroup>
</Project>
